name: tirth_today
description: "my portfolio site"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ^3.12.0-160.0.dev

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  font_awesome_flutter:
  google_fonts:
  video_player:
  page_flip:
  just_audio:
  get_it:
  flutter_card_swiper:
  flutter_drawing_board:
  flutter_markdown:
  youtube_player_iframe:
  pointer_interceptor:
  material_ui:
  web:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - 'assets/'
    - 'assets/Art/'
    - 'assets/animals_assets/'
    - 'assets/blogs_assets/'
    - 'assets/blogs/'
